# Generated by Django 4.2.7 on 2025-09-03 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('docker_image', models.CharField(max_length=200)),
                ('compile_command', models.TextField(blank=True)),
                ('execute_command', models.TextField()),
                ('file_extension', models.CharField(max_length=10)),
                ('default_code', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_execution_time', models.IntegerField(default=10)),
                ('max_memory_mb', models.IntegerField(default=512)),
                ('max_cpu_usage', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#3498db', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Problem Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='examsession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='initial_code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='test_results',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='memory_used',
        ),
        migrations.AddField(
            model_name='examsession',
            name='copy_paste_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='right_click_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='examsession',
            name='suspicious_activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='examsession',
            name='tab_switches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(default='No constraints specified'),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(default='Input description not provided'),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit_mb',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(default='Output description not provided'),
        ),
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_statement',
            field=models.TextField(default='Problem statement not provided'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit_seconds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.problem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='results_summary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(choices=[('sample', 'Sample'), ('public', 'Public'), ('private', 'Private'), ('stress', 'Stress')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='testcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='exams.problem'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='session_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='time_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.examsession'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('runtime_error', 'Runtime Error'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('compilation_error', 'Compilation Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='actual_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='exams.submission'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('current_rating', models.IntegerField(default=1200)),
                ('max_rating', models.IntegerField(default=1200)),
                ('rank', models.CharField(default='Unrated', max_length=20)),
                ('total_submissions', models.IntegerField(default=0)),
                ('accepted_submissions', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('contests_participated', models.IntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('video_recording', models.FileField(blank=True, null=True, upload_to='proctoring/videos/')),
                ('audio_recording', models.FileField(blank=True, null=True, upload_to='proctoring/audio/')),
                ('screen_recording', models.FileField(blank=True, null=True, upload_to='proctoring/screens/')),
                ('eye_tracking_data', models.JSONField(default=list)),
                ('keystroke_patterns', models.JSONField(default=list)),
                ('mouse_movements', models.JSONField(default=list)),
                ('face_detection_failures', models.IntegerField(default=0)),
                ('multiple_faces_detected', models.IntegerField(default=0)),
                ('no_face_detected_duration', models.IntegerField(default=0)),
                ('suspicious_objects_detected', models.JSONField(default=list)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('review_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_data', to='exams.examsession')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rules', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('contest_type', models.CharField(choices=[('practice', 'Practice'), ('rated', 'Rated Contest'), ('unrated', 'Unrated Contest'), ('virtual', 'Virtual Contest')], default='rated', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('invite_only', 'Invite Only')], default='public', max_length=20)),
                ('max_participants', models.IntegerField(default=10000)),
                ('registration_required', models.BooleanField(default=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enable_proctoring', models.BooleanField(default=False)),
                ('require_webcam', models.BooleanField(default=False)),
                ('require_microphone', models.BooleanField(default=False)),
                ('lock_browser', models.BooleanField(default=False)),
                ('allowed_languages', models.ManyToManyField(blank=True, to='exams.language')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='exams.contest'),
        ),
        migrations.AddField(
            model_name='submission',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.contest'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.language'),
        ),
        migrations.CreateModel(
            name='ProblemLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_code', models.TextField(default='')),
                ('solution_code', models.TextField(blank=True)),
                ('time_limit_override', models.IntegerField(blank=True, null=True)),
                ('memory_limit_override', models.IntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.problem')),
            ],
            options={
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_score', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('penalty_time', models.IntegerField(default=0)),
                ('last_submission_time', models.DateTimeField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('proctoring_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tab_switches', models.IntegerField(default=0)),
                ('suspicious_activities', models.IntegerField(default=0)),
                ('video_violations', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='exams.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', '-total_score', 'penalty_time'],
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CodeSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('similarity_type', models.CharField(max_length=50)),
                ('common_patterns', models.JSONField(default=list)),
                ('analysis_data', models.JSONField(default=dict)),
                ('is_flagged', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_checks_as_first', to='exams.submission')),
                ('submission2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_checks_as_second', to='exams.submission')),
            ],
            options={
                'unique_together': {('submission1', 'submission2')},
            },
        ),
    ]
