# Generated by Django 4.2.7 on 2025-09-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_language_problemcategory_alter_examsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
