# Generated by Django 4.2.7 on 2025-09-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_userprofile_aadhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
