# Generated by Django 4.2.7 on 2026-03-28 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='contests', to='exams.problem'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('coding', 'Coding Only'), ('mcq', 'MCQ Only'), ('hybrid', 'Hybrid (Coding + MCQ)')], default='coding', max_length=20),
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text='List of strings for options')),
                ('correct_option', models.IntegerField(help_text='0-indexed correct option')),
                ('marks', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='exams.contest')),
            ],
        ),
        migrations.CreateModel(
            name='MCQSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_submissions', to='exams.examsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.mcqquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam_session', 'question')},
            },
        ),
    ]
