# Generated by Django 4.2.7 on 2026-03-28 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0005_contest_problems_alter_contest_contest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsession',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
