# Generated by Django 4.2.7 on 2026-03-28 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examsession_marks_obtained_examsession_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='problems',
        ),
        migrations.AddField(
            model_name='contest',
            name='order_mcqs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('time_limit_override', models.IntegerField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.problem')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('contest', 'problem')},
            },
        ),
    ]
