# Generated by Django 4.2.7 on 2026-03-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_contest_problems_contest_order_mcqs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='contests', through='exams.ContestProblem', to='exams.problem'),
        ),
    ]
