# Generated by Django 4.2.7 on 2026-03-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_contest_problems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('violation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('frame_path', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_records', to='exams.examsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
