# Generated by Django 4.2.7 on 2026-03-28 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_proctoringrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestion',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='exams.contest'),
        ),
    ]
