# Generated by Django 4.2.7 on 2026-04-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_mcqsubmission_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='last_command',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
